const EventType = {
  FAVORITE_BUTTON_CLICK: 'FAVORITE_BUTTON_CLICK',
  POST_POINT: 'POST_POINT',
  DELETE_POINT: 'DELETE_POINT',
  UPDATE_POINT: 'UPDATE_POINT',
  UPDATE_DATA: 'UPDATE_DATE'
};

export { EventType };
